# Generated by Django 4.2.9 on 2024-01-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geronte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideeffectsrisks',
            name='title',
        ),
    ]
