# Generated by Django 4.2.9 on 2024-01-17 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geronte', '0002_remove_sideeffectsrisks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='drugs_allergies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geronte.sideeffectsrisks'),
        ),
    ]
