# Generated by Django 4.2.9 on 2024-01-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geronte', '0004_alter_patient_drugs_allergies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='drugs_allergies',
        ),
        migrations.AddField(
            model_name='sideeffectsrisks',
            name='patient',
            field=models.ManyToManyField(blank=True, related_name='drugs_allergies', to='geronte.patient'),
        ),
    ]
