# Generated by Django 4.2.9 on 2024-01-17 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geronte', '0005_remove_patient_drugs_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideeffectsrisks',
            name='patient',
        ),
        migrations.AddField(
            model_name='sideeffectsrisks',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geronte.patient'),
            preserve_default=False,
        ),
    ]
